MODEL:
  TYPE: mobilenet
  NUM_CLASSES: 1000
MB:
  WIDTH_MULT:  1.0
  STEM_W:      16
  STEM_ACT:    'swish'
  STRIDES:    [2,   2,  1,   2,   1,   1,  1,  1,  2,  1,   1]
  WIDTHS:     [16, 24, 24,  40,  40,  40, 48, 48, 96, 96,  96]
  EXP_RATIOS: [1, 4.5,3.6,   4,   6,   6,  3,  3,  6,  6,   6]
  KERNELS:    [3,   3,  3,   5,   5,   5,  5,  5,  5,  5,   5]
  SE_RARIOS:  [0.25,0,  0,0.25,0.25,0.25,0.25,0.25,0.25,0.25,0.25]
  ACTS:       ['relu', 'relu', 'relu','swish', 'swish', 'swish', 'swish', 'swish', 'swish', 'swish']
  HEAD_W:     [576, 1280]
  HEAD_ACTS:  ['swish', 'swish']
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.4
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-5
TRAIN:
  DATASET: imagenet
  IM_SIZE: 224
  BATCH_SIZE: 256
TEST:
  DATASET: imagenet
  IM_SIZE: 256
  BATCH_SIZE: 200
NUM_GPUS: 4
OUT_DIR: ./experiments/mobilenetv3small_dds_4gpu
