MODEL:
  TYPE: mobilenet
  NUM_CLASSES: 1000
MB:
  WIDTH_MULT:  1.0
  STEM_W:      16
  STEM_ACT:    'swish'
  STRIDES:    [1,   2,  1,   2,   1,   1,  2,  1,  1,  1,   1,   1,   1,   2,   1]
  WIDTHS:     [16, 24, 24,  40,  40,  40, 80, 80, 80, 80, 112, 112, 160, 160, 160]
  EXP_RATIOS: [1,   4,  3,   3,   3,   3,  6,2.5,2.3,2.3,   6,   6,   6, 4.2,   6]
  KERNELS:    [3,   3,  3,   5,   5,   5,  3,  3,  3,  3,   3,   3,   5,   5,   5]
  SE_RARIOS:  [0,   0,  0,0.25,0.25,0.25,  0,  0,  0,  0,0.25,0.25,0.25,0.25,0.25]
  ACTS:       ['relu', 'relu', 'relu', 'relu', 'relu', 'relu', 'swish', 'swish', 'swish', 'swish', 'swish', 'swish', 'swish', 'swish', 'swish']
  HEAD_W:     [960, 1280]
  HEAD_ACTS:  ['swish', 'swish']
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.4
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-5
TRAIN:
  DATASET: imagenet
  IM_SIZE: 224
  BATCH_SIZE: 256
TEST:
  DATASET: imagenet
  IM_SIZE: 256
  BATCH_SIZE: 200
NUM_GPUS: 8
OUT_DIR: .
